UBUNTU: Ubuntu-5.1.0-2.2
Signed-off-by: Seth Forshee <seth.forshee@canonical.com>

diff --git a/debian/tests/ubuntu-regression-suite b/debian/tests/ubuntu-regression-suite
--- a/debian/tests/ubuntu-regression-suite
+++ b/debian/tests/ubuntu-regression-suite
@@ -1,6 +1,32 @@
 #!/bin/sh
 set -e
 
+# Only run regression-suite on kernels we can boot in canonistack
+source=`dpkg-parsechangelog -SSource`
+case $source in
+    linux|linux-hwe|linux-kvm|linux-oem)
+	;;
+    *)
+	echo "ubuntu-regression-suite is pointless, if one cannot boot the kernel"
+	exit 77
+	;;
+esac
+
+# Only run regression-suite if we were requested to
+have_meta=0
+for trigger in ${ADT_TEST_TRIGGERS}
+do
+    case "$trigger" in
+	linux-meta/*|linux-meta-*/*)
+	    have_meta=1
+	    ;;
+    esac
+done
+if [ -n "$ADT_TEST_TRIGGERS" ] && [ "$have_meta" -eq 0 ]; then
+    echo "ubuntu-regression-suite is not requested, as there is no linux-meta trigger"
+    exit 77
+fi
+
 sver=`dpkg-parsechangelog -SVersion`
 read x rver x </proc/version_signature
 
