UBUNTU: [Packaging] correctly support the new ABI schema
The ABI directory is now <DEBIAN>abi/. Update the helper scripts to
properly support this naming when we need to re-use the previous ABI.

Also manually transition to the new ABI schema.

Signed-off-by: Andrea Righi <andrea.righi@canonical.com>

diff --git a/debian/scripts/helpers/open b/debian/scripts/helpers/open
--- a/debian/scripts/helpers/open
+++ b/debian/scripts/helpers/open
@@ -174,21 +174,14 @@ if [ -d "$DEBIAN/abi" ]; then
 	new=$(dpkg-parsechangelog -l"$DEBIAN/changelog" -SVersion)
 
 	if [ "$reuse_abi" -ne 0 ]; then
-		# Get the old ABI directory:
-		old=$(find "$DEBIAN/abi/" -mindepth 1 -maxdepth 1 -type d | \
-				  grep -P '/abi/[0-9]+\.[0-9]+\.[0-9]+-[0-9]+\.[0-9]+')
-		if [ -z "${old}" ] ; then
-			echo "Failed to find the previous ABI directory." \
-				 "Please check \"$DEBIAN/abi/\"!" >&2
-			exit 1
-		elif [ "$(echo "$old" | wc -l)" -gt 1 ]; then
-			echo "Failed to rename the current ABI directory." \
-			     "Multiple directories found. Please check \"$DEBIAN/abi/\"!" >&2
+		# Re-use ABI => simply update ABI version
+		abi_version="$DEBIAN/abi/version"
+		if ! [ -f "$abi_version" ]; then
+			echo "$abi_version ABI version file missing"
 			exit 1
 		fi
-		new="$DEBIAN/abi/$new"
-		# Rename the ABI directory
-		run git mv "$old" "$new"
+		echo $new > $abi_version
+		git add $abi_version
 	else
 		# Call in-tree getabis:
 		# Use the single argument form since getabis is now
@@ -204,13 +197,6 @@ run git add "$DEBIAN/changelog"
 
 # Create the commit
 run git commit -s -F debian/commit-templates/newrelease
-
-# Perform a basic ABI check
-if [ "$dry_run" -eq 0 ]; then
-	version=$(dpkg-parsechangelog -l"$DEBIAN/changelog" -SVersion -c1 -o1)
-	abi_dir="$DEBIAN/abi/$version"
-	[ ! -d "$abi_dir" ] && hl "Warning: ABI directory is missing: $abi_dir"
-fi
 
 # Mimic maint-startnewrelease
 [ "$dry_run" -eq 0 ] && \
